### ISSUE TITLE
Error downloading package for gero: self signed certificate in certificate chain and Node "gero" binPath is not available

### ISSUE THREAD

**Issue by Bambarello** [sero-cash/wallet#1]
** Please check - the following error when starting GUI wallet under Windows 7 and 10.**

```
D:\Wallet\SERO-Wallet>D:\Wallet\SERO-Wallet\SERO_Wallet.exe --node-datadir="D:\Wallet\SERO"

Settings.init begin =====
Settings.init end =====
Running in production mode: true
Settings.uiMode::: wallet
←[31m[2019-01-03 23:52:46.937] [ERROR] updateChecker - ←[39mError checking for update { RequestError
    at ClientRequest.req.once.err (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  message: 'self signed certificate in certificate chain',
  host: 'api.github.com',
  hostname: 'api.github.com',
  method: 'GET',
  path: '/repos/sero-cash/wallet/releases' }
latestConfig::: { clients: { gero: { version: '0.3.3-beta.rc.5-hotfix.3', platforms: [Object] } } }
process.getSystemMemoryInfo()::: { total: 8352644,
  free: 252056,
  swapTotal: 17566784,
  swapFree: 5710408 }
Exec: "where gero.exe"
←[31m[2019-01-03 23:52:47.619] [ERROR] ClientBinaryManager - ←[39mUnable to resolve gero executable: gero.exe
←[31m[2019-01-03 23:52:47.803] [ERROR] ClientBinaryManager - ←[39m{ RequestError
    at ClientRequest.req.once.err (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  message: 'self signed certificate in certificate chain',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/sero-cash/go-sero/releases/download/v0.3.3-beta.rc.5-hotfix.3/gero-v0.3.3-beta.rc.5-hotfix.3-windows-amd64.zip' }
←[31m[2019-01-03 23:52:47.806] [ERROR] ClientBinaryManager - ←[39mError: Error downloading package for gero: self signed certificate in certificate chain
    at DuplexWrapper.stream.on.err (D:\Wallet\SERO-Wallet\resources\app.asar\modules\seroClientBinaries.js:235:24)
    at emitOne (events.js:115:13)
    at DuplexWrapper.emit (events.js:210:7)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at ClientRequest.req.once.err (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\got\index.js:73:7)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Connect to {"path":"\\\\.\\pipe\\gero.ipc"}
←[33m[2019-01-03 23:52:47.825] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[33m[2019-01-03 23:52:48.826] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[33m[2019-01-03 23:52:49.828] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[31m[2019-01-03 23:52:50.829] [ERROR] Sockets/node-ipc - ←[39mConnection failed (3000ms elapsed)
←[33m[2019-01-03 23:52:50.830] [WARN] SeroNode - ←[39mFailed to connect to node. Maybe it's not running so let's start our own...
Start node: gero beta full
__startNode(nodeType, network, syncMode) gero beta full
client::: undefined
Node "gero" binPath is not available.
←[31m[2019-01-03 23:52:50.835] [ERROR] SeroNode - ←[39mFailed to start node Error: Node "gero" binPath is not available.
    at SeroNode.__startNode (D:\Wallet\SERO-Wallet\resources\app.asar\modules\seroNode.js:324:19)
    at stop.then (D:\Wallet\SERO-Wallet\resources\app.asar\modules\seroNode.js:260:25)
    at tryCatcher (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
←[31m[2019-01-03 23:52:50.838] [ERROR] main - ←[39mError starting up node and/or syncing Error: Node "gero" binPath is not available.
    at SeroNode.__startNode (D:\Wallet\SERO-Wallet\resources\app.asar\modules\seroNode.js:324:19)
    at stop.then (D:\Wallet\SERO-Wallet\resources\app.asar\modules\seroNode.js:260:25)
    at tryCatcher (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\Wallet\SERO-Wallet\resources\app.asar\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
←[31m[2019-01-03 23:57:33.458] [ERROR] main - ←[39mError shutting down sockets

```

**Comment by tomdurrent** [comment]
@Bambarello
hey, Have you set up https_proxy?

Please try opening the following URL in your browser. And check if normal access is possible.
https://github.com/sero-cash/go-sero/releases/download/v0.3.3-beta.rc.5-hotfix.3/gero-v0.3.3-beta.rc.5-hotfix.3-windows-amd64.zip

**In addition, you can configure gero manually.**
1. download the latest configuration file
URL:[http://sero-media.s3-website-ap-southeast-1.amazonaws.com/clients/clientBinaries.json](http://sero-media.s3-website-ap-southeast-1.amazonaws.com/clients/clientBinaries.json)
Download complete, overwrite configuration file in the following directory:
Windows `C:\Users\%username%\AppData\Roaming\SERO Wallet\clientBinaries.json`
macOS `~/Library/Application\ Support/SERO Wallet/clientBinaries.json`
Linux `~/.config/SERO Wallet/clientBinaries.json`

2. Download the gero compression package of the corresponding system,
URL:[https://github.com/sero-cash/go-sero/releases](https://github.com/sero-cash/go-sero/releases)
When the download is complete, copy the file to the following directory and name it archive.zip | tar, for example Windows archive.zip. Then extract it to the unpacked directory.
The correct directory structure after extracting is as follows:
Windows `C:\Users\%username%\AppData\Roaming\SERO Wallet\binaries\gero\unpacked\geropkg`
macOS `~/Library/Application\ Support/SERO Wallet/binaries/gero/unpacked/geropkg`
Linux `~/.config/SERO Wallet/binaries/gero/unpacked/geropkg`

3. Restart your SERO Wallet

**Comment by Bambarello** [comment]
Thank you for suggestions!

1) I'm able to open the release download links directly without issue. However Sero concole experiences isssues with GitHub, it's trying, but archive.zip file is with zero size.

2) I checked the config file is correct

3) downloaded compressed pack and extracted that to /gero/unpacked folder.

4) restart of Sero Wallet didn't help. But when I went to SERO Wallet/binaries/gero/unpacked/geropkg and started startup.bat - the local node started sync -> then I started GUI Wallet and it connected to local node successfully.

**Comment by tomdurrent** [comment]
Hey,Bambarello, I'm so sorry,One operation is missing in step 2, and that is copy /gero/geropkg/bin/gero.exe to /gero/unpacked/ , the "gero.exe" and "geropkg" are in the same directory as the folder.

Finally, congratulations, you've fixed it with a different way.
