### ISSUE TITLE
can't open the wallet by mac os

### ISSUE THREAD

**Issue by mailfly** [sero-cash/wallet#2]
![image](https://user-images.githubusercontent.com/10590409/61989495-d5194f00-b062-11e9-92bb-a12b36233787.png)

**Comment by mailfly** [comment]
![image](https://user-images.githubusercontent.com/10590409/61989516-245f7f80-b063-11e9-813c-47ed0474442e.png)

**Comment by mailfly** [comment]
mac os vesion is: OS X Yosemite : 10.10.5 (14F2511)

**Comment by gordon-sero** [comment]
@mailfly please put the detailed log here or te my mail <gordon@sero.vip>

the log path is : 
/Users/[YOUR USER NAME]/Library/Application Support/SERO Wallet/node.log

**Comment by mailfly** [comment]
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/lin/Library/Application Support/SERO Wallet/binaries/gero/unpacked/geropkg/czero/lib/libczero.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/lin/Library/Application Support/SERO Wallet/binaries/gero/unpacked/geropkg/czero/lib/libczero.dylib
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff61171075 m=0 sigcode=1

**Comment by mailfly** [comment]
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/lin/Library/Application Support/SERO Wallet/binaries/gero/unpacked/geropkg/czero/lib/libczero.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/lin/Library/Application Support/SERO Wallet/binaries/gero/unpacked/geropkg/czero/lib/libczero.dylib
  Expected in: /usr/lib/libSystem.B.dylib

SIGTRAP: trace trap
PC=0x7fff61171075 m=0 sigcode=1

goroutine 0 [idle]:
runtime: unknown pc 0x7fff61171075
stack: frame={sp:0x7fff5fbff0f8, fp:0x0} stack=[0x7fff5fb80bb0,0x7fff5fbffc20)
00007fff5fbfeff8:  0000044d699a011a  00007fff5fbff0f0 
00007fff5fbff008:  00007fff611719c0  0000000000000ecb 
00007fff5fbff018:  0000000007905830  0000000000000000 
00007fff5fbff028:  00007fff611971de  0000000000000000 
00007fff5fbff038:  00000000ff000000  0000000000000000 
00007fff5fbff048:  00007fff61197914  0000000000000007 
00007fff5fbff058:  00000000ff000000  000000000650f6c8 
00007fff5fbff068:  0000000006517350  00007fff611a8598 
00007fff5fbff078:  00007fff611af858  00007fff5fbff110 
00007fff5fbff088:  00007fff6118a0db  0000000000000000 
00007fff5fbff098:  0000000000000001  00007fff6119b4ca 
00007fff5fbff0a8:  0000000006517560  0000000000000000 
00007fff5fbff0b8:  00007fff86a54271  00007fff5fbff0f0 
00007fff5fbff0c8:  00007fff61191b46  0000000007905830 
00007fff5fbff0d8:  0000000007904db0  00007fff611a93f0 
00007fff5fbff0e8:  0000044d699a011a  00007fff5fbff110 
00007fff5fbff0f8: <00007fff61174169  0000000007905830 
00007fff5fbff108:  0000000000000ecb  00007fff5fbff130 
00007fff5fbff118:  00007fff611742a8  0000000000000001 
00007fff5fbff128:  000000000650d8ca  00007fff5fbff5a0 
00007fff5fbff138:  00007fff86a543ba  000000000000037f 
00007fff5fbff148:  0000000000000000  0000000000000000 
00007fff5fbff158:  0000ffff00001fa0  0000000000000000 
00007fff5fbff168:  000000000000ffff  0000000000000100 
00007fff5fbff178:  000000000000ffff  0000000000000000 
00007fff5fbff188:  0000000000000000  0000000000000000 
00007fff5fbff198:  0000000000000000  8fb8000000000000 
00007fff5fbff1a8:  000000000000c00b  8000000000000000 
00007fff5fbff1b8:  000000000000bffe  8000000000000000 
00007fff5fbff1c8:  0000000000004007  c060000000000000 
00007fff5fbff1d8:  000000000000400a  0000000000000000 
00007fff5fbff1e8:  0000000000000000  70412f7972617262 
runtime: unknown pc 0x7fff61171075
stack: frame={sp:0x7fff5fbff0f8, fp:0x0} stack=[0x7fff5fb80bb0,0x7fff5fbffc20)
00007fff5fbfeff8:  0000044d699a011a  00007fff5fbff0f0 
00007fff5fbff008:  00007fff611719c0  0000000000000ecb 
00007fff5fbff018:  0000000007905830  0000000000000000 
00007fff5fbff028:  00007fff611971de  0000000000000000 
00007fff5fbff038:  00000000ff000000  0000000000000000 
00007fff5fbff048:  00007fff61197914  0000000000000007 
00007fff5fbff058:  00000000ff000000  000000000650f6c8 
00007fff5fbff068:  0000000006517350  00007fff611a8598 
00007fff5fbff078:  00007fff611af858  00007fff5fbff110 
00007fff5fbff088:  00007fff6118a0db  0000000000000000 
00007fff5fbff098:  0000000000000001  00007fff6119b4ca 
00007fff5fbff0a8:  0000000006517560  0000000000000000 
00007fff5fbff0b8:  00007fff86a54271  00007fff5fbff0f0 
00007fff5fbff0c8:  00007fff61191b46  0000000007905830 
00007fff5fbff0d8:  0000000007904db0  00007fff611a93f0 
00007fff5fbff0e8:  0000044d699a011a  00007fff5fbff110 
00007fff5fbff0f8: <00007fff61174169  0000000007905830 
00007fff5fbff108:  0000000000000ecb  00007fff5fbff130 
00007fff5fbff118:  00007fff611742a8  0000000000000001 
00007fff5fbff128:  000000000650d8ca  00007fff5fbff5a0 
00007fff5fbff138:  00007fff86a543ba  000000000000037f 
00007fff5fbff148:  0000000000000000  0000000000000000 
00007fff5fbff158:  0000ffff00001fa0  0000000000000000 
00007fff5fbff168:  000000000000ffff  0000000000000100 
00007fff5fbff178:  000000000000ffff  0000000000000000 
00007fff5fbff188:  0000000000000000  0000000000000000 
00007fff5fbff198:  0000000000000000  8fb8000000000000 
00007fff5fbff1a8:  000000000000c00b  8000000000000000 
00007fff5fbff1b8:  000000000000bffe  8000000000000000 
00007fff5fbff1c8:  0000000000004007  c060000000000000 
00007fff5fbff1d8:  000000000000400a  0000000000000000 
00007fff5fbff1e8:  0000000000000000  70412f7972617262 

goroutine 9 [syscall]:
runtime.cgocall(0x48c11a0, 0xc0002b7fa0, 0x20)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc0002b7f70 sp=0xc0002b7f38 pc=0x4004e9e
github.com/sero-cash/go-czero-import/cpt._Cfunc_zero_init(0x7904c50, 0x2)
	_cgo_gotypes.go:271 +0x45 fp=0xc0002b7fa0 sp=0xc0002b7f70 pc=0x42ca955
github.com/sero-cash/go-czero-import/cpt.ZeroInit.func1(0xc00027fa40, 0x20, 0x2)
	/ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:58 +0x4c fp=0xc0002b7fc8 sp=0xc0002b7fa0 pc=0x42ce14c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0002b7fd0 sp=0xc0002b7fc8 pc=0x405ea71
created by github.com/sero-cash/go-czero-import/cpt.ZeroInit
	/ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:57 +0x52

goroutine 1 [chan receive]:
github.com/sero-cash/go-czero-import/cpt.ZeroInit(0xc00027fa40, 0x20, 0x2, 0x0, 0x4a9c100)
	/ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:64 +0x6b
main.init.0.func1(0xc0002a4580, 0x52bc8f8, 0xc00032e1a0)
	/ext-go/1/src/github.com/sero-cash/go-sero/cmd/gero/main.go:222 +0x5f8
github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00032e1a0, 0xc0000b2000, 0xb, 0xb, 0x0, 0x0)
	/ext-go/1/src/github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli.v1/app.go:241 +0x6ce
main.main()
	/ext-go/1/src/github.com/sero-cash/go-sero/cmd/gero/main.go:346 +0xad

goroutine 20 [chan receive]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.(*recursiveTree).dispatch(0xc0000d0280)
	/ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_recursive.go:125 +0xc7
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.newRecursiveTree
	/ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_recursive.go:119 +0x132

goroutine 21 [syscall, locked to thread]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	_cgo_gotypes.go:243 +0x41
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.init.1.func1()
	/ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:72 +0x57
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.init.1
	/ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:65 +0x4e

goroutine 22 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

**Comment by mailfly** [comment]
i think it's as by my mac os version is older

**Comment by mailfly** [comment]
i think it's as by my mac os version is older ,
this lib  /usr/lib/libSystem.B.dylib  ,don't have blow functions 
dyld: Symbol not found: _clock_gettime

nm -gU /usr/lib/libSystem.B.dylib
0000000000001af1 T R8289209$_close
0000000000001af6 T R8289209$_fork
0000000000001afb T R8289209$_fsync
0000000000001b00 T R8289209$_getattrlist
0000000000001b05 T R8289209$_getrlimit
0000000000001b0a T R8289209$_getxattr
0000000000001b0f T R8289209$_open
0000000000001b14 T R8289209$_pthread_attr_destroy
0000000000001b19 T R8289209$_pthread_attr_init
0000000000001b1e T R8289209$_pthread_attr_setdetachstate
0000000000001b23 T R8289209$_pthread_create
0000000000001b28 T R8289209$_pthread_mutex_lock
0000000000001b2d T R8289209$_pthread_mutex_unlock
0000000000001b32 T R8289209$_pthread_self
0000000000001b37 T R8289209$_ptrace
0000000000001b3c T R8289209$_read
0000000000001b41 T R8289209$_setattrlist
0000000000001b46 T R8289209$_setrlimit
0000000000001b4b T R8289209$_sigaction
0000000000001b50 T R8289209$_stat
0000000000001b55 T R8289209$_sysctl
0000000000001b5a T R8289209$_time
0000000000001b5f T R8289209$_unlink
0000000000001b64 T R8289209$_write
0000000000001f90 S ___System_BVersionNumber
0000000000001f60 S ___System_BVersionString
0000000000002298 S ___crashreporter_info__
0000000000001b69 T _libSystem_atfork_child
0000000000001ad3 T _libSystem_atfork_parent
0000000000001ab5 T _libSystem_atfork_prepare
0000000000002290 D _mach_init_routine

**Comment by mailfly** [comment]
btw ,could you suport the older  mac os version
