### ISSUE TITLE
Sero node crash (dont sync fully)

### ISSUE THREAD

**Issue by RedMeOne** [sero-cash/wallet#4]
[2020-02-29 19:22:57.082] [ERROR] ipcProviderBackend - Send request failed Error: Unable to connect to socket: timeout
    at Timeout.setTimeout [as _onTimeout] (D:\SERO\resources\app.asar\modules\sockets\base.js:94:39)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
[2020-02-29 19:22:57.083] [INFO] Sockets/2 - Connect to {"path":"\\\\.\\pipe\\gero.ipc"}
[2020-02-29 19:22:57.084] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2020-02-29 19:22:57.086] [INFO] (ui: browser) - {}
[2020-02-29 19:22:58.084] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...
[2020-02-29 19:22:59.084] [WARN] Sockets/2 - Connection failed, retrying after 1000ms...

Error in log. In sero wallet my account disappear
![s1](https://user-images.githubusercontent.com/61617338/75604885-1a39be00-5b29-11ea-9d19-8a5e0809505a.png)
[app.log](https://github.com/sero-cash/wallet/files/4270117/app.log)

 and stop sync

**Comment by RedMeOne** [comment]
![s2](https://user-images.githubusercontent.com/61617338/75604926-84eaf980-5b29-11ea-98f8-13d48b267f3b.png)
[app1.log](https://github.com/sero-cash/wallet/files/4270120/app1.log)
more logs after restart sero wallet

**Comment by RedMeOne** [comment]
Is it Sero network problem? Because I have a problem with explorer.sero.cash as 502 gateway error
![s3](https://user-images.githubusercontent.com/61617338/75609260-c3e17500-5b52-11ea-865f-b7f4d851de31.png)

**Comment by RedMeOne** [comment]
Is it Sero network problem? Because I have a problem with explorer.sero.cash as 502 gateway error
![s3](https://user-images.githubusercontent.com/61617338/75609260-c3e17500-5b52-11ea-865f-b7f4d851de31.png)
